### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by oldpotter** [leichunfeng/MVVMReactiveCocoa#102]
![Uploading error.png…]()

你好，按照你的步骤进行Pod install后报错了，不知是什么问题？

**Comment by leichunfeng** [comment]
看不到你的图片哦，建议先执行下 pod repo update ，再执行 pod install

**Comment by gonghonglou** [comment]
请问执行pod install 报如下错误怎么办呢？
[!] No podspec found for `WXTabBarController` in `WXTabBarController`
![](http://7xn9bi.com1.z0.glb.clouddn.com/error%2Finstallerror.png)

**Comment by leichunfeng** [comment]
请使用 `pod repo update` 更新下你本地 CocoaPods 的索引。

**Comment by gonghonglou** [comment]
将Podfile文件中`pod 'WXTabBarController', :path => 'WXTabBarController'`的`, :path => 'WXTabBarController'`删掉就OK了

**Comment by leichunfeng** [comment]
请直接使用 `README` 中的命令进行克隆。
