### ISSUE TITLE
开发 Trending repositories 界面

### ISSUE THREAD

**Issue by leichunfeng** [leichunfeng/MVVMReactiveCocoa#108]
![image](https://cloud.githubusercontent.com/assets/5253662/13903496/d24c9f80-eeb8-11e5-94cc-e8ba2b00aa51.png)

**Comment by leichunfeng** [comment]
1、界面内容

- 可以快速切换 `Daily` 、`Weekly` 和 `Monthly` 查看当前语言的 `Trending repositories` ；
- 点击右上角的设置按钮，跳转到 Language 界面，支持反显当前选中的语言，点击返回后，如果选择了不同的语言，则刷新界面。

**Comment by leichunfeng** [comment]
2、涉及到的接口

- 调用 [GitHub-Trending](https://github.com/thedillonb/GitHub-Trending) 提供的接口 http://trending.codehub-app.com/v2/trending ，通过语言和时间段来过滤，目前应用中已经有这部分功能，只需要调整下界面即可。

**Comment by leichunfeng** [comment]
Fixed

**Comment by Huang-Libo** [comment]
接口调用显示的trending和GitHub网页的trending不一致, 是爬取时间不同引起的吗
