### ISSUE TITLE
没法跑起来。。。

### ISSUE THREAD

**Issue by huangjunsong** [leichunfeng/MVVMReactiveCocoa#115]
我在podinstall的时候报了个错，AsyncDisplayKit没能装，
然后再次pod install，AsyncDisplayKit和其他库都装好了
但是依旧跑不起来Mantle-iOS库报错了，Build setting PRODUCT_NAME undefined
我build的是MVVMReactiveCocoa，是什么问题呢？
![Uploading Snip20160321_2.png…]()

**Comment by leichunfeng** [comment]
请问下是按照 README 中的命令操作的吗？

**Comment by huangjunsong** [comment]
代码我是用github desktop软件clone下来的，然后正常pod install

**Comment by leichunfeng** [comment]
这个项目有子模块，需要递归克隆子模块

**Comment by huangjunsong** [comment]
好的，我按照指令走一次

**Comment by leichunfeng** [comment]
好的

**Comment by huangjunsong** [comment]
我按照指令下载完了项目，但是在MVVMReactiveCocoa目录下pod install时报错了
Analyzing dependencies
Pre-downloading: `OcticonsIOS` from `https://github.com/jacksonh/OcticonsIOS.git`, commit `4bd3b21`
Fetching podspec for `WXTabBarController` from `WXTabBarController`
[!] No podspec found for `WXTabBarController` in `WXTabBarController`

[!] CocoaPods was not able to update the `artsy` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

**Comment by huangjunsong** [comment]
我先pod repo update看看

**Comment by leichunfeng** [comment]
你先运行 pod repo update 更新下索引吧，这里提示你更新索引失败

**Comment by leichunfeng** [comment]
不行的话，连接下 VPN

**Comment by huangjunsong** [comment]
在 clone的时候发生了一些错误，貌似有些文件没下下来
Cloning into 'Carthage/Checkouts/xcconfigs'...
fatal: unable to access 'https://github.com/jspahrsummers/xcconfigs.git/': Could not resolve host: github.com
Clone of 'https://github.com/jspahrsummers/xcconfigs.git' into submodule path 'Carthage/Checkouts/xcconfigs' failed
Cloning into 'Carthage/Checkouts/xcconfigs'...
fatal: unable to access 'https://github.com/jspahrsummers/xcconfigs.git/': Could not resolve host: github.com
Clone of 'https://github.com/jspahrsummers/xcconfigs.git' into submodule path 'Carthage/Checkouts/xcconfigs' failed
Cloning into 'WXTabBarController'...
fatal: unable to access 'https://github.com/leichunfeng/WXTabBarController.git/': Could not resolve host: github.com
Clone of 'https://github.com/leichunfeng/WXTabBarController.git' into submodule path 'WXTabBarController' failed

**Comment by huangjunsong** [comment]
不知道是不是公司的网络问题，我晚上回家开VPN试试看

**Comment by huangjunsong** [comment]
我已经跑起来了，果然是网络问题，如果完整把项目clone下来再pod install是没问题的，不行的建议大家换网试试，或者开vpn

**Comment by leichunfeng** [comment]
Good
