### ISSUE TITLE
[idea] support github oauth with safari view controller

### ISSUE THREAD

**Issue by dkhamsing** [leichunfeng/MVVMReactiveCocoa#117]
check out https://github.com/dkhamsing/GitHubOAuthController :sweat_smile:

**Comment by leichunfeng** [comment]
Thank you very much, related to #114

**Comment by dkhamsing** [comment]
Ah cool
Feel free to close if this is a duplicate

**Comment by leichunfeng** [comment]
Fixed

**Comment by dkhamsing** [comment]
Good deal!

Can you point to the code that uses safari view controller ?

**Comment by leichunfeng** [comment]
I don’t use safari view controller, but just the web view. The main classes are bellow:

[MRCOAuthViewController.m](https://github.com/leichunfeng/MVVMReactiveCocoa/blob/master/MVVMReactiveCocoa/View/MRCOAuthViewController.m)
[MRCOAuthViewModel.m](https://github.com/leichunfeng/MVVMReactiveCocoa/blob/master/MVVMReactiveCocoa/ViewModel/MRCOAuthViewModel.m)

I implement this feature according to your source code - [GitHubOAuthController](https://github.com/dkhamsing/GitHubOAuthController), thank you very much.

**Comment by dkhamsing** [comment]
Cool! Thx
