### ISSUE TITLE
Trending: The data Star and Fork from server is wrong

### ISSUE THREAD

**Issue by shenAlexy** [leichunfeng/MVVMReactiveCocoa#122]
I select Objective-C trending by Today, and I found the data Star and Fork form server is wrong. For instance, my repositories of shenAlexy/MVVM  Star and Fork is wrong!

**Comment by leichunfeng** [comment]
非常感谢你的反馈哈，Trending 功能使用的是第三方提供的接口，地址是 [GitHub-Trending](https://github.com/thedillonb/GitHub-Trending) ，这个接口应该是采用定时去采取 GitHub 的数据来实现的，更新并不会太及时。

另外，http://trending.codehub-app.com/v2/trending?since=daily&language=objective-c 这个是今天 Objective-C 的 Trending 接口， 我对比了你的库的 Star 和 Fork 数，确实会有一定的偏差，原因如上。

**Comment by shenAlexy** [comment]
ok , this qustion could be solved?

在 2016年4月18日 下午3:43，leichunfeng <notifications@github.com>写道：

**Comment by leichunfeng** [comment]
我想你可能得给这个库 [thedillonb/GitHub-Trending](https://github.com/thedillonb/GitHub-Trending) 提一个 `issue` ，不过我觉得这个问题是由这个库本身的机制决定的了
