### ISSUE TITLE
Install ReactiveCocoa

### ISSUE THREAD

**Issue by lichangsong** [leichunfeng/MVVMReactiveCocoa#124]
podfile 里面没有添加ReactiveCocoa，求教下ReactiveCocoa库没有使用Cocoapods管理吗

**Comment by leichunfeng** [comment]
通过子模块引入的

**Comment by foxsin10** [comment]
怎么通过子模块引入呢，pod 完之后运行提示缺少ReactiveCocoa库。在podfile中加入ReactiveCocoa，pod完会报错

**Comment by leichunfeng** [comment]
请按照 `README` 中的命令进行操作

**Comment by foxsin10** [comment]
执行完运行workspace提示未引入 ReactiveCocoa. 和使用downloadzip下载的项目文件一样，downloadzip文件的podfile可以在打开workspace文件后打开，里边也没有引入ReactiveCocoa

**Comment by leichunfeng** [comment]
麻烦提供一下你运行整个命令的截图

**Comment by foxsin10** [comment]
已经好了，可能公司网络不行，有几个包没下完给的警告，没报错。在家里边慢慢下完运行没问题
