### ISSUE TITLE
在MRCProfileViewController有闪退bug

### ISSUE THREAD

**Issue by jianjianhao** [leichunfeng/MVVMReactiveCocoa#125]
点击头像闪退

<img width="761" alt="9afad206-1125-46c1-92d8-e7d56ae8829f" src="https://cloud.githubusercontent.com/assets/12797357/14839633/1890903c-0c5f-11e6-8d36-b996439bd121.png">

**Comment by leichunfeng** [comment]
感谢反馈，我这边试了下好像不会闪退，可以帮忙解决一下吗？

**Comment by jianjianhao** [comment]
我的是运行环境Xcode7.2 模拟器iPhone6s

**Comment by leichunfeng** [comment]
请问下你的账号是一定会出现闪退吗？我的账号没有重现得了

**Comment by jianjianhao** [comment]
对的

**Comment by leichunfeng** [comment]
恩，那我可以借你的账号和密码用一下吗？可以的话，麻烦发一下到我的邮箱 307213080@qq.com ，谢谢啊。

**Comment by jianjianhao** [comment]
雷大神收到邮件请回复一下，没有我再发一次

**Comment by leichunfeng** [comment]
没有收到包含有你的账号和密码的邮件哦

**Comment by jianjianhao** [comment]
雷大神，我把一句代码注释了就不奔溃了
<img width="712" alt="fdb21851-a3bd-4e76-bb84-00e43928406d" src="https://cloud.githubusercontent.com/assets/12797357/14845188/32821bd4-0c8f-11e6-8482-8985b1d6a760.png">
具体原因不太清楚，我也是刚刚开始学mvvm + rac

**Comment by leichunfeng** [comment]
这句代码我已经优化掉了，麻烦更新下代码，验证下是否已解决这个问题，谢谢。

**Comment by leichunfeng** [comment]
Fixed
