### ISSUE TITLE
请问下类图是用什么工具生成的

### ISSUE THREAD

**Issue by Wilson2014** [leichunfeng/MVVMReactiveCocoa#129]

**Comment by leichunfeng** [comment]
直接用 OmniGraffle 生成的

**Comment by Wilson2014** [comment]
谢谢！不过这软件好贵啊

**Comment by huanghe810229530** [comment]
具体生成步骤是怎么样的，可以说说吗？ @leichunfeng

**Comment by leichunfeng** [comment]
直接将包含有 Xcode 工程文件的目录拖到 OmniGraffle 的应用图标上即可。

**Comment by songxing10000** [comment]
@leichunfeng 那样不会生成你项目里的线连起来的样式啊，我试过了，
感觉你那种线连起来的很清晰，请求方法
