### ISSUE TITLE
[optimize] Using Safari to Log in, but cancel it

### ISSUE THREAD

**Issue by shenAlexy** [leichunfeng/MVVMReactiveCocoa#130]
If I use safari to login, the program will jump to the safari, and pop-up prompts, I click cancel at this time, still stay in safari, I returned to the software, it has been showed that Logging in!

**Comment by shenAlexy** [comment]
![Uploading 06A0586221F0C9A4A1C42342D8ED7644.png…]()

**Comment by shenAlexy** [comment]
![Uploading 06A0586221F0C9A4A1C42342D8ED7644.png…]()

**Comment by leichunfeng** [comment]
最新的代码已经使用的 OAuth2 授权了哦，请更新到最新的代码试试。

**Comment by shenAlexy** [comment]
ok.

**Comment by shenAlexy** [comment]
Developer applications里怎么设置应用的Authorization callback URL？

**Comment by leichunfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/5253662/15988369/73117a40-3080-11e6-86d2-7cbc87ce9d7f.png)
