### ISSUE TITLE
TencentOpenAPI/QQApiInterface.h file not found

### ISSUE THREAD

**Issue by samlaudev** [leichunfeng/MVVMReactiveCocoa#133]
执行完一下命令之后
git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install

编译错误：
TencentOpenAPI/QQApiInterface.h file not found

**Comment by leichunfeng** [comment]
可以放一下截图吗？

**Comment by samlaudev** [comment]
<img width="882" alt="screen shot 2016-06-12 at 8 09 19 pm" src="https://cloud.githubusercontent.com/assets/2336442/15991050/a0b3d304-30d9-11e6-96b7-e18d700f787f.png">

**Comment by leichunfeng** [comment]
PODS:
  - Appirater (2.0.5)
  - AsyncDisplayKit (1.9.73):
    - AsyncDisplayKit/PINRemoteImage (= 1.9.73)
  - AsyncDisplayKit/ASDealloc2MainObject (1.9.73)
  - AsyncDisplayKit/Core (1.9.73):
    - AsyncDisplayKit/ASDealloc2MainObject
  - AsyncDisplayKit/PINRemoteImage (1.9.73):
    - AsyncDisplayKit/Core
    - PINRemoteImage/iOS (>= 3.0.0-beta.2)
  - Bugtags (1.2.5)
  - DZNEmptyDataSet (1.5.2)
  - FMDB (2.6.2):
    - FMDB/standard (= 2.6.2)
  - FMDB/standard (2.6.2)
  - FormatterKit (1.8.1):
    - FormatterKit/AddressFormatter (= 1.8.1)
    - FormatterKit/ArrayFormatter (= 1.8.1)
    - FormatterKit/ColorFormatter (= 1.8.1)
    - FormatterKit/LocationFormatter (= 1.8.1)
    - FormatterKit/NameFormatter (= 1.8.1)
    - FormatterKit/OrdinalNumberFormatter (= 1.8.1)
    - FormatterKit/Resources (= 1.8.1)
    - FormatterKit/TimeIntervalFormatter (= 1.8.1)
    - FormatterKit/UnitOfInformationFormatter (= 1.8.1)
    - FormatterKit/URLRequestFormatter (= 1.8.1)
  - FormatterKit/AddressFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/ArrayFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/ColorFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/LocationFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/NameFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/OrdinalNumberFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/Resources (1.8.1)
  - FormatterKit/TimeIntervalFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/UnitOfInformationFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/URLRequestFormatter (1.8.1):
    - FormatterKit/Resources
  - GPUImage (0.1.7)
  - IQKeyboardManager (3.2.0.3)
  - LCFInfiniteScrollView (0.1):
    - SDWebImage
  - MBProgressHUD (0.9.2)
  - MKNetworkKit (0.87):
    - Reachability (~> 3.1.0)
  - OcticonsIOS (0.0.2)
  - Ono (1.2.2)
  - PINCache (2.2.2)
  - PINRemoteImage/Core (3.0.0-beta.2):
    - PINCache (>= 2.1)
  - PINRemoteImage/iOS (3.0.0-beta.2):
    - PINRemoteImage/Core
  - Reachability (3.1.1)
  - SDVersion (2.6)
  - SDWebImage (3.7.6):
    - SDWebImage/Core (= 3.7.6)
  - SDWebImage/Core (3.7.6)
  - SSKeychain (1.2.3)
  - SVPullToRefresh (0.4.1)
  - UIActivityIndicator-for-SDWebImage (1.2):
    - SDWebImage (~> 3.7)
  - UMengSocial (4.4)
  - WebViewJavascriptBridge (4.1.5)
  - YYKit (1.0.5):
    - YYKit/no-arc (= 1.0.5)
  - YYKit/no-arc (1.0.5)

DEPENDENCIES:
  - Appirater
  - AsyncDisplayKit
  - Bugtags
  - DZNEmptyDataSet (~> 1.5.1)
  - FMDB
  - FormatterKit (~> 1.8.0)
  - GPUImage (~> 0.1.7)
  - IQKeyboardManager (~> 3.2.0.3)
  - LCFInfiniteScrollView (from `https://github.com/leichunfeng/LCFInfiniteScrollView.git`)
  - MBProgressHUD (~> 0.9)
  - MKNetworkKit (~> 0.87)
  - OcticonsIOS (from `https://github.com/jacksonh/OcticonsIOS.git`, commit `4bd3b21`)
  - Ono (~> 1.2.0)
  - SDVersion
  - SDWebImage (~> 3.7.1)
  - SSKeychain (~> 1.2.2)
  - SVPullToRefresh (~> 0.4.1)
  - UIActivityIndicator-for-SDWebImage
  - UMengSocial (~> 4.3)
  - WebViewJavascriptBridge (~> 4.1.4)
  - YYKit

EXTERNAL SOURCES:
  LCFInfiniteScrollView:
    :git: https://github.com/leichunfeng/LCFInfiniteScrollView.git
  OcticonsIOS:
    :commit: 4bd3b21
    :git: https://github.com/jacksonh/OcticonsIOS.git

CHECKOUT OPTIONS:
  LCFInfiniteScrollView:
    :commit: 790c256212c610c72127e57f945fbe4064cde98a
    :git: https://github.com/leichunfeng/LCFInfiniteScrollView.git
  OcticonsIOS:
    :commit: 4bd3b21
    :git: https://github.com/jacksonh/OcticonsIOS.git

SPEC CHECKSUMS:
  Appirater: e7c0a47fb67ee5041ce8479e6ba960927fb40264
  AsyncDisplayKit: cc906c5ddff9d34c8f5ea2f18ba092033c5516a3
  Bugtags: 577b6c56e5540d5f29e060b1eb050078dfce9084
  DZNEmptyDataSet: 741da409081a4bf707c949c964623a6ad1799772
  FMDB: 854a0341b4726e53276f2a8996f06f1b80f9259a
  FormatterKit: 11ad17b983200629246a5a466f6f1bfa2df823cb
  GPUImage: 733a5f0fab92df9de1c37ba9df520a833ccb406d
  IQKeyboardManager: 7b071d1284b47b1c0c19891a042c2c65f118fa85
  LCFInfiniteScrollView: 6552dc73dd573ecd54d8e151e3a1a742722723f7
  MBProgressHUD: 1569cf7ace17a8bac47aabfbb8580a49690386d1
  MKNetworkKit: 60ad3c83b62183e40ba75ce772c9427c25b520de
  OcticonsIOS: e21204b48b0d83f7740008abed42f8b1573b3ffc
  Ono: 80b1c686777d3f6d5d5ce6fcac8a74afef4ca197
  PINCache: 078426d356ab95ef875e9e62e5c35a2ea3333c28
  PINRemoteImage: 197554c5ba57a6ae90f5db441651180039fc9062
  Reachability: dd9aa4fb6667b9f787690a74f53cb7634ce99893
  SDVersion: c036f7890279d188c17f5701b9feea0d93b9f8ee
  SDWebImage: c325cf02c30337336b95beff20a13df489ec0ec9
  SSKeychain: 3f42991739c6c60a9cf1bbd4dff6c0d3694bcf3d
  SVPullToRefresh: ba2e718695a43253d8bea6852d2960097dc15d8c
  UIActivityIndicator-for-SDWebImage: 7bf7ebbf0ed1747dedc0d6e949c4603a6d0f9e0c
  UMengSocial: aba7296602310385114d82c255539a7bef3b7ab0
  WebViewJavascriptBridge: e7b6669bebfc4f151daa0fdec3c8c24c8dc3a24e
  YYKit: f2654fe525de2283648db957bddb37ddd8e06549

COCOAPODS: 0.38.2

这个是我本地 Podfile.lock 文件的内容，里面显示使用的 UMengSocial 的版本是 4.4 ，请看下你那边是什么版本的？

**Comment by samlaudev** [comment]
UMengSocial (~> 4.3)

**Comment by samlaudev** [comment]
PODS:
  - Appirater (2.0.5)
  - AsyncDisplayKit (1.9.73):
    - AsyncDisplayKit/PINRemoteImage (= 1.9.73)
  - AsyncDisplayKit/ASDealloc2MainObject (1.9.73)
  - AsyncDisplayKit/Core (1.9.73):
    - AsyncDisplayKit/ASDealloc2MainObject
  - AsyncDisplayKit/PINRemoteImage (1.9.73):
    - AsyncDisplayKit/Core
    - PINRemoteImage/iOS (>= 3.0.0-beta.2)
  - Bugtags (1.2.5)
  - DZNEmptyDataSet (1.5.2)
  - FMDB (2.6.2):
    - FMDB/standard (= 2.6.2)
  - FMDB/standard (2.6.2)
  - FormatterKit (1.8.1):
    - FormatterKit/AddressFormatter (= 1.8.1)
    - FormatterKit/ArrayFormatter (= 1.8.1)
    - FormatterKit/ColorFormatter (= 1.8.1)
    - FormatterKit/LocationFormatter (= 1.8.1)
    - FormatterKit/NameFormatter (= 1.8.1)
    - FormatterKit/OrdinalNumberFormatter (= 1.8.1)
    - FormatterKit/Resources (= 1.8.1)
    - FormatterKit/TimeIntervalFormatter (= 1.8.1)
    - FormatterKit/UnitOfInformationFormatter (= 1.8.1)
    - FormatterKit/URLRequestFormatter (= 1.8.1)
  - FormatterKit/AddressFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/ArrayFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/ColorFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/LocationFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/NameFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/OrdinalNumberFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/Resources (1.8.1)
  - FormatterKit/TimeIntervalFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/UnitOfInformationFormatter (1.8.1):
    - FormatterKit/Resources
  - FormatterKit/URLRequestFormatter (1.8.1):
    - FormatterKit/Resources
  - GPUImage (0.1.7)
  - IQKeyboardManager (3.2.0.3)
  - LCFInfiniteScrollView (0.1):
    - SDWebImage
  - MBProgressHUD (0.9.2)
  - MKNetworkKit (0.87):
    - Reachability (~> 3.1.0)
  - OcticonsIOS (0.0.2)
  - Ono (1.2.2)
  - PINCache (2.2.2)
  - PINRemoteImage/Core (3.0.0-beta.2):
    - PINCache (>= 2.1)
  - PINRemoteImage/iOS (3.0.0-beta.2):
    - PINRemoteImage/Core
  - Reachability (3.1.1)
  - SDVersion (2.6)
  - SDWebImage (3.7.6):
    - SDWebImage/Core (= 3.7.6)
  - SDWebImage/Core (3.7.6)
  - SSKeychain (1.2.3)
  - SVPullToRefresh (0.4.1)
  - UIActivityIndicator-for-SDWebImage (1.2):
    - SDWebImage (~> 3.7)
  - UMengSocial (4.4)
  - WebViewJavascriptBridge (4.1.5)
  - YYKit (1.0.5):
    - YYKit/no-arc (= 1.0.5)
  - YYKit/no-arc (1.0.5)

DEPENDENCIES:
  - Appirater
  - AsyncDisplayKit
  - Bugtags
  - DZNEmptyDataSet (~> 1.5.1)
  - FMDB
  - FormatterKit (~> 1.8.0)
  - GPUImage (~> 0.1.7)
  - IQKeyboardManager (~> 3.2.0.3)
  - LCFInfiniteScrollView (from `https://github.com/leichunfeng/LCFInfiniteScrollView.git`)
  - MBProgressHUD (~> 0.9)
  - MKNetworkKit (~> 0.87)
  - OcticonsIOS (from `https://github.com/jacksonh/OcticonsIOS.git`, commit `4bd3b21`)
  - Ono (~> 1.2.0)
  - SDVersion
  - SDWebImage (~> 3.7.1)
  - SSKeychain (~> 1.2.2)
  - SVPullToRefresh (~> 0.4.1)
  - UIActivityIndicator-for-SDWebImage
  - UMengSocial (~> 4.3)
  - WebViewJavascriptBridge (~> 4.1.4)
  - YYKit

EXTERNAL SOURCES:
  LCFInfiniteScrollView:
    :git: https://github.com/leichunfeng/LCFInfiniteScrollView.git
  OcticonsIOS:
    :commit: 4bd3b21
    :git: https://github.com/jacksonh/OcticonsIOS.git

CHECKOUT OPTIONS:
  LCFInfiniteScrollView:
    :commit: 790c256212c610c72127e57f945fbe4064cde98a
    :git: https://github.com/leichunfeng/LCFInfiniteScrollView.git
  OcticonsIOS:
    :commit: 4bd3b21
    :git: https://github.com/jacksonh/OcticonsIOS.git

SPEC CHECKSUMS:
  Appirater: e7c0a47fb67ee5041ce8479e6ba960927fb40264
  AsyncDisplayKit: cc906c5ddff9d34c8f5ea2f18ba092033c5516a3
  Bugtags: 577b6c56e5540d5f29e060b1eb050078dfce9084
  DZNEmptyDataSet: 741da409081a4bf707c949c964623a6ad1799772
  FMDB: 854a0341b4726e53276f2a8996f06f1b80f9259a
  FormatterKit: 11ad17b983200629246a5a466f6f1bfa2df823cb
  GPUImage: 733a5f0fab92df9de1c37ba9df520a833ccb406d
  IQKeyboardManager: 7b071d1284b47b1c0c19891a042c2c65f118fa85
  LCFInfiniteScrollView: 6552dc73dd573ecd54d8e151e3a1a742722723f7
  MBProgressHUD: 1569cf7ace17a8bac47aabfbb8580a49690386d1
  MKNetworkKit: 60ad3c83b62183e40ba75ce772c9427c25b520de
  OcticonsIOS: e21204b48b0d83f7740008abed42f8b1573b3ffc
  Ono: 80b1c686777d3f6d5d5ce6fcac8a74afef4ca197
  PINCache: 078426d356ab95ef875e9e62e5c35a2ea3333c28
  PINRemoteImage: 197554c5ba57a6ae90f5db441651180039fc9062
  Reachability: dd9aa4fb6667b9f787690a74f53cb7634ce99893
  SDVersion: c036f7890279d188c17f5701b9feea0d93b9f8ee
  SDWebImage: c325cf02c30337336b95beff20a13df489ec0ec9
  SSKeychain: 3f42991739c6c60a9cf1bbd4dff6c0d3694bcf3d
  SVPullToRefresh: ba2e718695a43253d8bea6852d2960097dc15d8c
  UIActivityIndicator-for-SDWebImage: 7bf7ebbf0ed1747dedc0d6e949c4603a6d0f9e0c
  UMengSocial: aba7296602310385114d82c255539a7bef3b7ab0
  WebViewJavascriptBridge: e7b6669bebfc4f151daa0fdec3c8c24c8dc3a24e
  YYKit: f2654fe525de2283648db957bddb37ddd8e06549

COCOAPODS: 0.39.0

**Comment by samlaudev** [comment]
友盟的版本都一样，但是你使用的是COCOAPODS: 0.38.2，我使用的是COCOAPODS: 0.39.0

**Comment by leichunfeng** [comment]
那应该是 CocoaPods 0.39 的问题了，这几天我会直接升级到 CocoaPods 1.0 版本，目前已经有一个单独的分支 cocoapods-1.0 支持  CocoaPods 1.0 的了，有兴趣的话可以直接尝试 clone 这个分支试试，CocoaPods 0.39 之后头文件的搜索路径有些变动，所以会出现这样的问题

**Comment by leichunfeng** [comment]
现在 `master` 分支的代码已经是使用 `CocoaPods 1.0.1` 的了，请将 `CocoaPods` 升级到 `1.0+` ，然后重新执行一下整个操作，谢谢。

**Comment by samlaudev** [comment]
还是不行，我已经将CocoaPods升级到1.0.1，删除之前的项目文件，再执行
git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install
还是出现这个编译问题！

**Comment by samlaudev** [comment]
还是不行，我已经将CocoaPods升级到1.0.1
<img width="603" alt="screen shot 2016-06-17 at 12 25 56 pm" src="https://cloud.githubusercontent.com/assets/2336442/16140769/d01b9a90-3486-11e6-95a3-fe0cd2a41486.png">
删除之前的项目文件，再执行
git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install
还是出现这个编译问题！

**Comment by leichunfeng** [comment]
我刚把 Pods 文件夹删除掉，重新运行 pod install 之后也还是可以编译通过的哦，下面是我的项目的 Header Search Paths ：

![image](https://cloud.githubusercontent.com/assets/5253662/16142367/3e319b3c-3497-11e6-9ca3-9c9a5314f1f9.png)

**Comment by samlaudev** [comment]
我也一样
<img width="556" alt="screen shot 2016-06-17 at 2 47 40 pm" src="https://cloud.githubusercontent.com/assets/2336442/16142760/b9334422-349a-11e6-8608-32aaf822dab2.png">

**Comment by duanhjlt** [comment]
我也是同样的问题，pod使用的是1.0.1，请问解决了吗？ @samlaudev 
我搜了一下，并没有这2个文件，于是我就把这2个头文件注释了，结果提示，ld: library not found for -lAPOpenSdk。这个文件我也没有找到。使用的是模拟器6s

**Comment by leichunfeng** [comment]
我还是把 Pods 文件夹，以及 workspace 文件加到版本控制里面吧，不然每个人的环境都不太一样，自己去 pod install 可能会出现各种奇葩问题。

**Comment by duanhjlt** [comment]
看到你更新的pods了，我重新clone的代码，没有执行pod install。错误依旧。

**Comment by leichunfeng** [comment]
我把本地的项目发你邮箱，你看看可以编译不？

**Comment by duanhjlt** [comment]
duanhjlt@163.com

**Comment by leichunfeng** [comment]
已经发到你的邮箱了

**Comment by duanhjlt** [comment]
呵呵，我公司的电脑直接clone的，没有问题。家里的确实不行，可能和编译环境有关，晚上我再试试。

**Comment by leichunfeng** [comment]
好的，那我就把 Pods 文件夹和 workspace 文件保留到版本控制中了。

**Comment by duanhjlt** [comment]
我又来了，是因为我的一个个人小项目想用UMengSocial。我的个人电脑pod进去支持，直接出现这个错误提示。应该是UMengSocial本身的问题。我只好从pod中移除，直接添加到工程中就ok了。参照http://dev.umeng.com/social/ios/quick-integration

**Comment by prettyxfan** [comment]
请问你们解决了吗？我原来的pod版本是0.39.0，clone下来报这个错误，升级到1.1.1还是同样报错。除了把UMengSocial直接加到工程中还有别的办法吗？

**Comment by leichunfeng** [comment]
@prettyxfan 直接使用 `README` 中的命令克隆的话应该没有问题的吧

**Comment by prettyxfan** [comment]
@leichunfeng 是直接用git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git 弄下来的，pod install 前后都是同样的问题

**Comment by leichunfeng** [comment]
请直接使用 `README` 中的命令进行克隆。
