### ISSUE TITLE
Mantle/Mantle.h file not found

### ISSUE THREAD

**Issue by taohy** [leichunfeng/MVVMReactiveCocoa#136]
![image](https://cloud.githubusercontent.com/assets/9939752/16030117/fcd291a0-3220-11e6-9db9-6fc51ea320c4.png)
我按照教程说的，先clone,再install，然后编译的时候就出现这个问题，问一下，是怎么回事。

**Comment by leichunfeng** [comment]
git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install

是用这些命令的吗？

**Comment by taohy** [comment]
是，就是这个操作。

**Comment by leichunfeng** [comment]
麻烦提供一个运行这些命令的截图哈，看看过程中有没有出错

**Comment by taohy** [comment]
那等我重新弄一下。

**Comment by taohy** [comment]
![image](https://cloud.githubusercontent.com/assets/9939752/16033534/11820df6-323f-11e6-8dc6-5d74bffdb693.png)
![image](https://cloud.githubusercontent.com/assets/9939752/16033556/39d6e9d4-323f-11e6-9f81-aaab21851228.png)
![image](https://cloud.githubusercontent.com/assets/9939752/16033567/482d4cb2-323f-11e6-8a11-7dc4b8aca34c.png)
![image](https://cloud.githubusercontent.com/assets/9939752/16033626/a08dff32-323f-11e6-8ee7-d9e944c9147e.png)

从上往下依次是clone, cd ,install的命令结果；最后一个是历史命令截图。

**Comment by leichunfeng** [comment]
你的 CocoaPods 是 1.0 的么？

**Comment by taohy** [comment]
![image](https://cloud.githubusercontent.com/assets/9939752/16034219/1648cae2-3243-11e6-8dea-82cc34edb270.png)
是这个

**Comment by leichunfeng** [comment]
请看下这个目录里面有没有 Mantle 文件夹？

![image](https://cloud.githubusercontent.com/assets/5253662/16034469/9cae7d42-3244-11e6-8f69-2e4ab4bab5ed.png)

**Comment by taohy** [comment]
![image](https://cloud.githubusercontent.com/assets/9939752/16034939/fe4207ac-3246-11e6-9eaf-5024fe564ff2.png)
有

**Comment by leichunfeng** [comment]
奇怪了，可以麻烦你用 0.38.2 版本的 CocoaPods 试一下吗？

**Comment by taohy** [comment]
好吧，我试试。可能要今晚先，你先忙其他的吧。

**Comment by leichunfeng** [comment]
OK

**Comment by taohy** [comment]
![image](https://cloud.githubusercontent.com/assets/9939752/16038753/253aa4d8-3259-11e6-9d0d-af6078787408.png)
![image](https://cloud.githubusercontent.com/assets/9939752/16038772/3be65b1e-3259-11e6-9abb-7e159fd4f0f4.png)
![image](https://cloud.githubusercontent.com/assets/9939752/16038809/5f567c46-3259-11e6-8421-50f22d470ac7.png)
![image](https://cloud.githubusercontent.com/assets/9939752/16038826/712c0b34-3259-11e6-984d-178d535517e9.png)
![image](https://cloud.githubusercontent.com/assets/9939752/16038857/84a7f5d8-3259-11e6-9725-4c6f716a7b52.png)

还是有问题哦。

**Comment by leichunfeng** [comment]
我也重新 clone 一下看看

**Comment by leichunfeng** [comment]
Last login: Tue Jun 14 09:16:43 on ttys000
➜  ~ git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
Cloning into 'MVVMReactiveCocoa'...
remote: Counting objects: 11226, done.
remote: Total 11226 (delta 0), reused 0 (delta 0), pack-reused 11226
Receiving objects: 100% (11226/11226), 8.33 MiB | 588.00 KiB/s, done.
Resolving deltas: 100% (7090/7090), done.
Checking connectivity... done.
Submodule 'OctoKit' (https://github.com/leichunfeng/octokit.objc.git) registered for path 'OctoKit'
Cloning into 'OctoKit'...
remote: Counting objects: 5843, done.
remote: Total 5843 (delta 0), reused 0 (delta 0), pack-reused 5843
Receiving objects: 100% (5843/5843), 1.59 MiB | 302.00 KiB/s, done.
Resolving deltas: 100% (3703/3703), done.
Checking connectivity... done.
Submodule path 'OctoKit': checked out 'bd2ad04b0947ca0717c787335db5ed1b686f81d7'
Submodule 'Carthage/Checkouts/Mantle' (https://github.com/Mantle/Mantle.git) registered for path 'Carthage/Checkouts/Mantle'
Submodule 'Carthage/Checkouts/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Carthage/Checkouts/Nimble'
Submodule 'Carthage/Checkouts/Quick' (https://github.com/Quick/Quick.git) registered for path 'Carthage/Checkouts/Quick'
Submodule 'Carthage/Checkouts/ReactiveCocoa' (https://github.com/ReactiveCocoa/ReactiveCocoa.git) registered for path 'Carthage/Checkouts/ReactiveCocoa'
Submodule 'Carthage/Checkouts/xcconfigs' (https://github.com/jspahrsummers/xcconfigs.git) registered for path 'Carthage/Checkouts/xcconfigs'
Submodule 'External/AFNetworking' (https://github.com/github/AFNetworking.git) registered for path 'External/AFNetworking'
Submodule 'External/ISO8601DateFormatter' (https://github.com/boredzo/iso-8601-date-formatter.git) registered for path 'External/ISO8601DateFormatter'
Submodule 'External/OHHTTPStubs' (https://github.com/github/OHHTTPStubs.git) registered for path 'External/OHHTTPStubs'
Cloning into 'Carthage/Checkouts/Mantle'...
remote: Counting objects: 5392, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5392 (delta 0), reused 0 (delta 0), pack-reused 5390
Receiving objects: 100% (5392/5392), 1.45 MiB | 213.00 KiB/s, done.
Resolving deltas: 100% (3354/3354), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle': checked out 'f797bd4837b61d37847a4833024aab268599a681'
Submodule 'Carthage.checkout/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Carthage/Checkouts/Nimble'
Submodule 'Carthage.checkout/Quick' (https://github.com/Quick/Quick.git) registered for path 'Carthage/Checkouts/Quick'
Submodule 'Carthage.checkout/xcconfigs' (https://github.com/jspahrsummers/xcconfigs.git) registered for path 'Carthage/Checkouts/xcconfigs'
Cloning into 'Carthage/Checkouts/Nimble'...
remote: Counting objects: 4544, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4544 (delta 0), reused 0 (delta 0), pack-reused 4538
Receiving objects: 100% (4544/4544), 919.75 KiB | 334.00 KiB/s, done.
Resolving deltas: 100% (3103/3103), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle/Carthage/Checkouts/Nimble': checked out '6f787eeb75b2fa71464981f28b3dc8d7bd532e69'
Cloning into 'Carthage/Checkouts/Quick'...
remote: Counting objects: 5174, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 5174 (delta 8), reused 0 (delta 0), pack-reused 5148
Receiving objects: 100% (5174/5174), 1.65 MiB | 487.00 KiB/s, done.
Resolving deltas: 100% (3115/3115), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle/Carthage/Checkouts/Quick': checked out 'b0e98286db7e9d1f1e73cd4e69eac2aae2a1e3f8'
Submodule 'Externals/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Externals/Nimble'
Cloning into 'Externals/Nimble'...
remote: Counting objects: 4544, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4544 (delta 0), reused 0 (delta 0), pack-reused 4538
Receiving objects: 100% (4544/4544), 919.75 KiB | 430.00 KiB/s, done.
Resolving deltas: 100% (3103/3103), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle/Carthage/Checkouts/Quick/Externals/Nimble': checked out '56c3b79d5a32686fe5529d7aa305000b489ebdaa'
Cloning into 'Carthage/Checkouts/xcconfigs'...
remote: Counting objects: 637, done.
remote: Total 637 (delta 0), reused 0 (delta 0), pack-reused 637
Receiving objects: 100% (637/637), 114.58 KiB | 154.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle/Carthage/Checkouts/xcconfigs': checked out '6c64238566ef1126f1b7994aa9e6719229c50451'
Cloning into 'Carthage/Checkouts/Nimble'...
remote: Counting objects: 4544, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4544 (delta 0), reused 0 (delta 0), pack-reused 4538
Receiving objects: 100% (4544/4544), 919.75 KiB | 315.00 KiB/s, done.
Resolving deltas: 100% (3103/3103), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Nimble': checked out '6f787eeb75b2fa71464981f28b3dc8d7bd532e69'
Cloning into 'Carthage/Checkouts/Quick'...
remote: Counting objects: 5174, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 5174 (delta 8), reused 0 (delta 0), pack-reused 5148
Receiving objects: 100% (5174/5174), 1.65 MiB | 421.00 KiB/s, done.
Resolving deltas: 100% (3115/3115), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Quick': checked out 'b0e98286db7e9d1f1e73cd4e69eac2aae2a1e3f8'
Submodule 'Externals/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Externals/Nimble'
Cloning into 'Externals/Nimble'...
remote: Counting objects: 4544, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4544 (delta 0), reused 0 (delta 0), pack-reused 4538
Receiving objects: 100% (4544/4544), 919.75 KiB | 367.00 KiB/s, done.
Resolving deltas: 100% (3103/3103), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Quick/Externals/Nimble': checked out '56c3b79d5a32686fe5529d7aa305000b489ebdaa'
Cloning into 'Carthage/Checkouts/ReactiveCocoa'...
remote: Counting objects: 41300, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 41300 (delta 0), reused 0 (delta 0), pack-reused 41293
Receiving objects: 100% (41300/41300), 15.76 MiB | 114.00 KiB/s, done.
Resolving deltas: 100% (24514/24514), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa': checked out '32364b9040dee9975053398bcf89f3f94a8341cd'
Submodule 'Carthage/Checkouts/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Carthage/Checkouts/Nimble'
Submodule 'Carthage/Checkouts/Quick' (https://github.com/Quick/Quick.git) registered for path 'Carthage/Checkouts/Quick'
Submodule 'Carthage/Checkouts/xcconfigs' (https://github.com/jspahrsummers/xcconfigs.git) registered for path 'Carthage/Checkouts/xcconfigs'
Cloning into 'Carthage/Checkouts/Nimble'...
remote: Counting objects: 4544, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4544 (delta 0), reused 0 (delta 0), pack-reused 4538
Receiving objects: 100% (4544/4544), 919.75 KiB | 353.00 KiB/s, done.
Resolving deltas: 100% (3103/3103), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Nimble': checked out '8927113f877f32c8a01b41b746c4ac261b42c48e'
Cloning into 'Carthage/Checkouts/Quick'...
remote: Counting objects: 5174, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 5174 (delta 8), reused 0 (delta 0), pack-reused 5148
Receiving objects: 100% (5174/5174), 1.65 MiB | 299.00 KiB/s, done.
Resolving deltas: 100% (3115/3115), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick': checked out '8bf96f708924d728dab5f0cf7543b6f1b896a209'
Submodule 'Externals/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Externals/Nimble'
Cloning into 'Externals/Nimble'...
remote: Counting objects: 4544, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 4544 (delta 0), reused 0 (delta 0), pack-reused 4538
Receiving objects: 100% (4544/4544), 919.75 KiB | 225.00 KiB/s, done.
Resolving deltas: 100% (3103/3103), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick/Externals/Nimble': checked out '6a9a1036c0604119c5567e45916149e16f251152'
Cloning into 'Carthage/Checkouts/xcconfigs'...
remote: Counting objects: 637, done.
remote: Total 637 (delta 0), reused 0 (delta 0), pack-reused 637
Receiving objects: 100% (637/637), 114.58 KiB | 150.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/xcconfigs': checked out '2e77204b59c3d97c24e5dd34966fb32c231194f0'
Cloning into 'Carthage/Checkouts/xcconfigs'...
remote: Counting objects: 637, done.
remote: Total 637 (delta 0), reused 0 (delta 0), pack-reused 637
Receiving objects: 100% (637/637), 114.58 KiB | 138.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/xcconfigs': checked out 'b09b4b63235b760a3a48a8dd19c0415aaaa8f269'
Cloning into 'External/AFNetworking'...
remote: Counting objects: 10866, done.
remote: Total 10866 (delta 0), reused 0 (delta 0), pack-reused 10866
Receiving objects: 100% (10866/10866), 3.75 MiB | 547.00 KiB/s, done.
Resolving deltas: 100% (6994/6994), done.
Checking connectivity... done.
Submodule path 'OctoKit/External/AFNetworking': checked out 'e364bf509249c43282784b9595b3284145ddbba9'
Cloning into 'External/ISO8601DateFormatter'...
remote: Counting objects: 1165, done.
remote: Total 1165 (delta 0), reused 0 (delta 0), pack-reused 1165
Receiving objects: 100% (1165/1165), 285.00 KiB | 148.00 KiB/s, done.
Resolving deltas: 100% (704/704), done.
Checking connectivity... done.
Submodule path 'OctoKit/External/ISO8601DateFormatter': checked out '35f4248b2747dee9716c9f59ccada16862a5278c'
Cloning into 'External/OHHTTPStubs'...
remote: Counting objects: 1398, done.
remote: Total 1398 (delta 0), reused 0 (delta 0), pack-reused 1398
Receiving objects: 100% (1398/1398), 349.09 KiB | 219.00 KiB/s, done.
Resolving deltas: 100% (892/892), done.
Checking connectivity... done.
Submodule path 'OctoKit/External/OHHTTPStubs': checked out '8761af63dc87ef8dd3944f2248ac4e1f6256c4c8'
➜  ~ cd MVVMReactiveCocoa
➜  MVVMReactiveCocoa git:(master) podi
Analyzing dependencies
Pre-downloading: `LCFInfiniteScrollView` from `https://github.com/leichunfeng/LCFInfiniteScrollView.git`, commit `790c256212c610c72127e57f945fbe4064cde98a`
^C[!] Cancelled
➜  MVVMReactiveCocoa git:(master) pod --version
0.38.2
➜  MVVMReactiveCocoa git:(master) podi
Analyzing dependencies
Pre-downloading: `LCFInfiniteScrollView` from `https://github.com/leichunfeng/LCFInfiniteScrollView.git`, commit `790c256212c610c72127e57f945fbe4064cde98a`
Pre-downloading: `OcticonsIOS` from `https://github.com/jacksonh/OcticonsIOS.git`, commit `4bd3b21`
Downloading dependencies
Installing Appirater (2.0.5)
Installing AsyncDisplayKit (1.9.73)
^C[!] Cancelled
➜  MVVMReactiveCocoa git:(master) podi
Analyzing dependencies
Pre-downloading: `LCFInfiniteScrollView` from `https://github.com/leichunfeng/LCFInfiniteScrollView.git`, commit `790c256212c610c72127e57f945fbe4064cde98a`
Pre-downloading: `OcticonsIOS` from `https://github.com/jacksonh/OcticonsIOS.git`, commit `4bd3b21`
Downloading dependencies
Using Appirater (2.0.5)
Installing AsyncDisplayKit (1.9.73)
Installing Bugtags (1.2.5)
Installing DZNEmptyDataSet (1.5.2)
Installing FMDB (2.6.2)
Installing FormatterKit (1.8.1)
Installing GPUImage (0.1.7)
Installing IQKeyboardManager (3.2.0.3)
Installing LCFInfiniteScrollView (0.1)
Installing MBProgressHUD (0.9.2)
Installing MKNetworkKit (0.87)
Installing OcticonsIOS (0.0.2)
Installing Ono (1.2.2)
Installing PINCache (2.2.2)
Installing PINRemoteImage (3.0.0-beta.2)
Installing Reachability (3.1.1)
Installing SDVersion (2.6)
Installing SDWebImage (3.7.6)
Installing SSKeychain (1.2.3)
Installing SVPullToRefresh (0.4.1)
Installing UIActivityIndicator-for-SDWebImage (1.2)
Installing UMengSocial (4.4)
Installing WebViewJavascriptBridge (4.1.5)
Installing YYKit (1.0.5)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `MVVMReactiveCocoa.xcworkspace` for this project from now on.
Sending stats
➜  MVVMReactiveCocoa git:(master)

我重新整个 clone 了一次，是可以编译成功的

**Comment by taohy** [comment]
可能是我电脑的问题，我自己去看看。还是要感谢你的耐心指导啦。

**Comment by leichunfeng** [comment]
现在 `master` 分支的代码已经是使用 `CocoaPods 1.0.1` 的了，请将 `CocoaPods` 升级到 `1.0+` ，然后重新执行一下整个操作，谢谢。

**Comment by taohy** [comment]
我昨天clone下来，然后各种改搜索路径，可以用了。
下午有空我再用1.0+clone下来试试。

**Comment by leichunfeng** [comment]
是的，因为从 `CocoaPods 0.39` 开始，头文件的搜索路径规则有些变化。

**Comment by taohy** [comment]
刚用1.0.1版本试了一下，还是有问题。估计是我电脑的问题。

**Comment by leichunfeng** [comment]
还是报一样的错吗？

**Comment by taohy** [comment]
嗯

**Comment by leichunfeng** [comment]
麻烦你把工程压缩一下发给我，我跑一下看看，我的 QQ 邮箱是 307213080@qq.com

**Comment by taohy** [comment]
发了

**Comment by leichunfeng** [comment]
我直接用你发给我的工程，可以编译成功啊，我的 Xcode 版本是 7.3 的

**Comment by leichunfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/5253662/16140416/d5af6346-3482-11e6-829a-9e2e2de5e403.png)

**Comment by leichunfeng** [comment]
我刚把 Pods 文件夹删除掉，重新运行 pod install 之后也还是可以编译通过的哦，下面是我的项目的 Header Search Paths ：

![image](https://cloud.githubusercontent.com/assets/5253662/16142367/3e319b3c-3497-11e6-9ca3-9c9a5314f1f9.png)

**Comment by HePingLaoSan** [comment]
我怀疑他打开的是project。。。 @leichunfeng

**Comment by leichunfeng** [comment]
请直接使用 `README` 中的命令进行克隆。
