### ISSUE TITLE
怎么实现隔页面的跳转呢？

### ISSUE THREAD

**Issue by LarkNan** [leichunfeng/MVVMReactiveCocoa#159]
你好，请问怎么实现隔页面的跳转呢？

比如：A push到 B，B push到 C，C push到D。 然后D怎么一步返回到B页面呢？
OC中可以使用下面的代码，那么在这个项目中怎么去实现这样的跳转呢？

` self.navigationController popToViewController: animated:`

或者，有什么其他方法可以实现这种效果。

**Comment by leichunfeng** [comment]
如果有需要的话，可以参考现有的方法实现一个这样的方法。

**Comment by LarkNan** [comment]
嗯嗯，昨天发完消息后自己试着写了下。下面是我写的代码，请看下。

`[[(NSObject *)self.services
      rac_signalForSelector:@selector(popToViewModel:animated:)]
     subscribeNext:^(RACTuple *tuple) {
        	@strongify(self)
         UIViewController *viewController = (UIViewController *)[ETRouter.sharedInstance viewControllerForViewModel:tuple.first];
         
         for (UIViewController *controller in [self.navigationControllers.lastObject childViewControllers]) {
             if ([controller isKindOfClass:[viewController class]]) {
                 [self.navigationControllers.lastObject popToViewController:controller animated:YES];
             }
         }
     }];`
