### ISSUE TITLE
Feedback from sugarkaka

### ISSUE THREAD

**Issue by sugarkaka** [leichunfeng/MVVMReactiveCocoa#163]
能不能直接默认适配手机屏幕呢，不需要再点一下右上角

**Comment by leichunfeng** [comment]
没太明白你的意思哦

**Comment by sugarkaka** [comment]
抱歉，没有讲清楚。

是这样，我的手机是iPhone6s，在进入代码主页后显示图不完整，需要左右滑动，如图一：
![default](https://cloud.githubusercontent.com/assets/16687553/18113209/72e0329a-6f60-11e6-9a24-206ea30bfecb.jpg)

我需要点击右上角选项，点击Enable wrapping 才会完整显示代码，如图二：
![default](https://cloud.githubusercontent.com/assets/16687553/18113214/78ed1252-6f60-11e6-9e89-f58639a046a8.jpg)

所以能否直接默认打开代码即是 Enable wrapping 的形式（图二）？
![default](https://cloud.githubusercontent.com/assets/16687553/18113203/6bce2cfa-6f60-11e6-9ee3-8b2f959cf3f9.jpg)

建议不太成熟，只是一点个人想法，谢谢！

**Comment by leichunfeng** [comment]
谢谢你的建议，我考虑把这个做成记住用户上次的设置。
