### ISSUE TITLE
必现bug

### ISSUE THREAD

**Issue by liujiaboy** [leichunfeng/MVVMReactiveCocoa#168]
两个必现的bug
iOS10 iPhone 7P 模拟器
1、下拉刷新、结束之后一直存在下拉刷新的视图
2、push之后，手势右滑返回出现空白视图，取消返回并造成界面错乱
![simulator screen shot 2016 9 23 10 29 25](https://cloud.githubusercontent.com/assets/17328307/18772695/ad284cee-817b-11e6-82b5-f1e97f9736f8.png)
![814f7938-40bd-4fc3-9456-35bab511b879](https://cloud.githubusercontent.com/assets/17328307/18772699/b0a38bc2-817b-11e6-963e-6fdc4d09014f.png)
![simulator screen shot 2016 9 23 10 50 11](https://cloud.githubusercontent.com/assets/17328307/18772704/b56c80d2-817b-11e6-8ad6-198c940dff18.png)

**Comment by leichunfeng** [comment]
感谢反馈
