### ISSUE TITLE
ReactiveCocoa/ReactiveCocoa.h file not found

### ISSUE THREAD

**Issue by alexLayer** [leichunfeng/MVVMReactiveCocoa#174]
哥们 半年前就看下了您这个 改了好久运行不了 昨天又用scoureTree 和 你推荐的命令行方式都不行 我的pod版本是1.1.1 方便加一下qq吗

**Comment by linkjd** [comment]
兄弟，我也遇到了类似的问题，怎么解决啊？

**Comment by leichunfeng** [comment]
请问下是使用 `README` 中介绍的命令操作的吗？

**Comment by linkjd** [comment]
你好，我是直接download下来的，没有clone

**Comment by linkjd** [comment]
哦哦，好的，感谢指点

**Comment by alexLayer** [comment]
我弄好了 重新用readme命令行下载就可以 用sourceTree还是有问题
