### ISSUE TITLE
Feedback from xmliu

### ISSUE THREAD

**Issue by xmliu** [leichunfeng/MVVMReactiveCocoa#177]
搜索好像搜不到指定的库

**Comment by leichunfeng** [comment]
哪个库搜索不到？

**Comment by linzb93** [comment]
是啊，搜索问题有几个月了。以jQuery和Vue为例（两个star数量都超过40000了），电脑上的第一个搜索结果就是了。app上，jQuery搜了十几个搜不到，vue的也没有找到，而且搜索结果一共10个不到。貌似去年五六月的时候还没问题的。

**Comment by leichunfeng** [comment]
指定一下 JavaScript 语言搜索一下试试看

**Comment by linzb93** [comment]
没问题了，谢谢。。

**Comment by leichunfeng** [comment]
不客气
