### ISSUE TITLE
Dependency Analysis Error

### ISSUE THREAD

**Issue by TouAllCra** [leichunfeng/MVVMReactiveCocoa#181]
When i bulit it ,but it's error with dependency analysis error.

None of your accounts are a member of 'V45CY933KN':  An unexpected error occurred. Xcode cannot find a team matching 'V45CY933KN'.
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "V45CY933KN" with a private key was found.

sorry about this,i can't found about this.

**Comment by leichunfeng** [comment]
如果是模拟器运行的话，去掉就好了；如果是真机的话，请换成你自己的账号。
