### ISSUE TITLE
Please Consider Using your Own Trending Server

### ISSUE THREAD

**Issue by thedillonb** [leichunfeng/MVVMReactiveCocoa#183]
The endpoint, `trending.codehub-app.com`, is used primarily for CodeHub and so it's scale has been designed around supporting that user base. However, your application is also using that endpoint which is generating additional load and bandwidth on the server. Please consider using something else or standing your own server up. [GitHub-Trending](https://github.com/thedillonb/GitHub-Trending) is the code that is used to power that server and is simple to setup.

**Comment by leichunfeng** [comment]
Thank you for your feedback. I will deal with it as soon as possible.

**Comment by leichunfeng** [comment]
Already fixed and I'm so sorry for the trouble brings to you.
