### ISSUE TITLE
Cannot find interface declaration for 'OCTRef'

### ISSUE THREAD

**Issue by zhjzh** [leichunfeng/MVVMReactiveCocoa#187]
OCTRef+MRCUtil.h的文件中，下面这句代码报Cannot find interface declaration for 'OCTRef'
@interface OCTRef (MRCUtil)

**Comment by FannCyii** [comment]
我也遇到这问题，换了各种版本的OctoKit，都有问题……求解

**Comment by leichunfeng** [comment]
请用 `README` 中的命令进行一键克隆。

**Comment by FannCyii** [comment]
欧拉，谢谢了
