### ISSUE TITLE
编译不通过怎么解决？

### ISSUE THREAD

**Issue by 1738004401** [leichunfeng/MVVMReactiveCocoa#188]
<img width="872" alt="1" src="https://cloud.githubusercontent.com/assets/17542303/23006225/8b718a24-f43b-11e6-9843-029d8985d6f9.png">

直接clone下来，编译不通过，请问需要其它设置么？

**Comment by leichunfeng** [comment]
请直接使用 `README` 中介绍的命令克隆。

**Comment by CancerQ** [comment]
github desktop 克隆可以
