### ISSUE TITLE
没注释看的好蛋疼

### ISSUE THREAD

**Issue by JW-chenjingwei** [leichunfeng/MVVMReactiveCocoa#209]
大神为什么没有一处是有注释的呢?想学习都看得好累啊...

**Comment by tangzzz-fan** [comment]
博客上有一篇讲了, 你可以去看看

**Comment by leichunfeng** [comment]
看看这篇文章[《MVVM With ReactiveCocoa》](http://blog.leichunfeng.com/blog/2016/02/27/mvvm-with-reactivecocoa/)
