### ISSUE TITLE
Feedback from lumangmang

### ISSUE THREAD

**Issue by lumangmang** [leichunfeng/MVVMReactiveCocoa#210]
Yyy

**Comment by tangzzz-fan** [comment]
你为什么总是开这些没有用的 issue ? 如果有问题, 请及时按照一定格式提出来, 如果没有问题, 请不要开一些无聊的 issue.

**Comment by leichunfeng** [comment]
这些 issue 是从 GitBucket 客户端的意见反馈里面来的，有些人喜欢去测试意见反馈功能，可能觉得好玩吧。
