### ISSUE TITLE
Fix bug

### ISSUE THREAD

**Issue by adamseib** [leichunfeng/MVVMReactiveCocoa#212]
{"app_name":"Unknown","app_version":"","bug_type":"144","timestamp":"2017-05-16 02:56:14.95 -0500","os_version":"iPhone OS 10.3.1 (14E304)","incident_id":"0C659C18-EF3A-4DB2-961B-331BEB35D68F","slice_uuid":"","build_version":"","is_first_party":true,"share_with_app_devs":true,"name":"Unknown"}
Date/Time:       2017-05-15 00:00:00 -0500
OS Version:      iPhone OS 10.3.1 (Build 14E304)
Architecture:    arm64
Report Version:  19

**Comment by leichunfeng** [comment]
?
