### ISSUE TITLE
Feedback from c-ly

### ISSUE THREAD

**Issue by c-ly** [leichunfeng/MVVMReactiveCocoa#214]
终于编译通过跑起来了，希望雷神给个指南，方便后人😂😂😂😂😂

**Comment by leichunfeng** [comment]
根据 `README` 来克隆的话，还会遇到什么其他问题吗？

**Comment by LJJHD** [comment]
请问你是怎么编译通过的，我的老是找不到文件

**Comment by c-ly** [comment]
有试过readme的方式，不过太慢了，只有10k左右速度，也可能是我这边的问题。说下我的方式：我是clone的最近的一个版本，git clone --depth=1 https://github.com/c-ly/MVVMReactiveCocoa.git，然后git submodule update --recursive, 之后报了一些错误，例如未定义的product name，一些库找不到头文件等等，然后我就自己定义了product name，然后调整了一些库在项目中的位置，还有AFN的报的只能在ARC环境下编译，然后我又加上-fobjc-arc的flag等等，搞了一下午终于搞定。。。

在 2017-06-01 17:47:14，"leichunfeng" <notifications@github.com> 写道：


根据 README 来克隆的话，还会遇到什么其他问题吗？

**Comment by c-ly** [comment]
@LJJHD 你最好先试试readme里边的方式，毕竟官方的方式，我是遇到了速度问题等不及才另觅出路，不过特别折腾，并不推荐，建议按照雷神的来，实在不行再试试我的方法

**Comment by leichunfeng** [comment]
对的啊，通过 `README` 中的一条命令就可以了
