### ISSUE TITLE
git error!

### ISSUE THREAD

**Issue by RPGLiker** [leichunfeng/MVVMReactiveCocoa#225]
git clone --recursive https：// github.com/leichunfeng/MVVMReactiveCocoa.git
    git config --global core.compression  - 1
这两句命令会导致git和cocoapods无法使用
    **fatal: bad numeric config value '-' for 'core.compression': invalid unit**
<img width="567" alt="2017-11-08 11 21 54" src="https://user-images.githubusercontent.com/20294470/32530230-8a003932-c402-11e7-82eb-18acab95a56a.png">

**Comment by leichunfeng** [comment]
git config --global core.compression -1

是 -1 不是 - 1
