### ISSUE TITLE
reason: 'Invalid parameter not satisfying: [NSClassFromString(viewController) isSubclassOfClass:[TLBaseViewController class]]'

### ISSUE THREAD

**Issue by loveUUU** [leichunfeng/MVVMReactiveCocoa#231]
NSString *viewController = self.viewModelViewMappings[NSStringFromClass(viewModel.class)];
你好，这个viewmodel的class  是 TLHomeInViewModel_RACSelectorSignal， 多了个后缀，直接崩溃，请问rac会自己做处理吗

**Comment by leichunfeng** [comment]
如果在 TLHomeInViewModel 类里面有用到 RACObserve 宏的话，就会把这个类改成 TLHomeInViewModel_RACSelectorSignal 的。

**Comment by loveUUU** [comment]
TLHomeInViewModel 里面我还没有编写代码，resetRootViewModel 这里我传入了 TLHomeInViewModel，在里面初始化了 4个 viewmodel，从tuple.first 拿到的就已经是带_RACSelectorSignal后缀的了。不知道如何解决，谢谢。
