### ISSUE TITLE
适配 iPhone X 和 iOS 11

### ISSUE THREAD

**Issue by leichunfeng** [leichunfeng/MVVMReactiveCocoa#234]

**Comment by Geazy96** [comment]
#234

**Comment by Geazy96** [comment]
https://www.eventbrite.com/print-ticket/748703478/43907636-748703478-tickets.pdf/?c=MjAxOC0wMy0yNSAxNzo0NzoxMw%3D%3D%0A&utm_source=eb_email&utm_medium=email&utm_campaign=order_confirm&sig=AHTu1yYhAnSqtoxAkPxhuCj0rPTj290Imw
