### ISSUE TITLE
iphone6 打开应用 就闪退

### ISSUE THREAD

**Issue by justsolive** [leichunfeng/MVVMReactiveCocoa#37]
iphone6 首次安装没问题 第二次打开时 就开始闪退 永远打不开应用了

**Comment by leichunfeng** [comment]
感谢反馈，这个问题我已经修复了，已经申请加急审核中。
另外想确认一下，你是使用邮箱登录的吗？并且用户信息里面没有填写邮箱吧？

**Comment by MVVMReactiveCocoa** [comment]
Fixed.
