### ISSUE TITLE
pod install时候报错了，改了两行podfile

### ISSUE THREAD

**Issue by calvingit** [leichunfeng/MVVMReactiveCocoa#41]
- 第一个是OcticonsIOS，因为我电脑已经有github的ssh key了，原先带用户名的链接是不行的，说认证失败。改成下面这个
```
pod 'OcticonsIOS', :git => 'https://github.com/jacksonh/OcticonsIOS.git', :commit => '4bd3b21'
```
- 第二个是FDFullscreenPopGesture，pod spec里面还是1.0版本，所以指定的1.1报错。我直接指向最新的提交就可以了
```
pod 'FDFullscreenPopGesture', :git => 'https://github.com/forkingdog/FDFullscreenPopGesture', :commit => 'da1efbf5'
```

**Comment by leichunfeng** [comment]
非常感谢反馈哈，事实上用 README 中的命令 clone 后是不需要再运行其他任何命令的，另外：

1. OcticonsIOS 这个库确实修改成 HTTPS 的方式会更好，这样不管有没有配置 SSH Key 的用户都可以更新 Pod ；
2. FDFullscreenPopGesture 已经出了 1.1 版本了，不然我也不会修改成 1.1 的，请更新一下你本地的 pod spec 索引。
