### ISSUE TITLE
Profile头像问题

### ISSUE THREAD

**Issue by zhanjiarong** [leichunfeng/MVVMReactiveCocoa#48]
大神，刚发现一个小问题。如果我的手机没有没有锁定屏幕旋转的话，并且我横屏点击Profile中的头像，头像显示出来的位置有问题，此时再竖屏也有问题。iPhone 6 Plus下。

**Comment by leichunfeng** [comment]
非常感谢反馈，我刚测试了下确实存在这个问题。另外，如果你有兴趣的话不妨提交一个 PR 解决这个问题哈。

**Comment by zhanjiarong** [comment]
我Reactive还不会，暂时解决了不这个问题。

**Comment by leichunfeng** [comment]
Fixed
