### ISSUE TITLE
代码中可以加上详细注释以及思路吗？还有整个程序的框架结构等等注解？可以借鉴MJ

### ISSUE THREAD

**Issue by zdrzdr** [leichunfeng/MVVMReactiveCocoa#50]
不然你写了这么多，看着特累

**Comment by leichunfeng** [comment]
这个建议非常好，我也有打算慢慢加上中文注释。

**Comment by maibou8888** [comment]
真的很希望雷大神可以把代码加上注释，或者用一个博客介绍一下产品，粉丝将不胜感激

**Comment by leichunfeng** [comment]
@maibou8888 非常感谢你们的宝贵意见哈，我后面会写一篇文章介绍一下这个项目的架构的，不过现在暂时没有时间，不仅有全职的工作要忙，而且为了能更好地理解 RAC 我也正在利用业余时间学习 Haskell ，大概是国庆之后的某个时间吧。

**Comment by hongdong** [comment]
好难看懂、注解说明有了吗？

**Comment by leichunfeng** [comment]
非常抱歉，应该不会等太久了哈，可以先加入 ReactiveCocoa 讨论群 430033580 交流下哈。

**Comment by leichunfeng** [comment]
你们要的文章[《MVVM With ReactiveCocoa》](http://blog.leichunfeng.com/blog/2016/02/27/mvvm-with-reactivecocoa/)终于来了，久等了哈。

**Comment by leichunfeng** [comment]
@zdrzdr @maibou8888 @hongdong
