### ISSUE TITLE
下载本项目后, 我没有运行起来 pch 文件中报错 提示 #import <ReactiveCocoa/ReactiveCocoa.h>

### ISSUE THREAD

**Issue by jiexishede** [leichunfeng/MVVMReactiveCocoa#51]
我自己在项目所在文件中执行了 pod install 和pod update , 还是提示这个错误. 请问作者如何解决, 我在百度上没有搜索到相关信息,.

**Comment by leichunfeng** [comment]
请看 [#49](https://github.com/leichunfeng/MVVMReactiveCocoa/issues/49) 。

**Comment by jiexishede** [comment]
十分感谢作者. 必须star, 期待作者的注释版..
