### ISSUE TITLE
编译报错，无法找到文件

### ISSUE THREAD

**Issue by bupojung** [leichunfeng/MVVMReactiveCocoa#59]
MVVMReactiveCocoa/MVVMReactiveCocoa/MVVMReactiveCocoa-Prefix.pch:15:13: 'ReactiveCocoa/ReactiveCocoa.h' file not found

**Comment by bupojung** [comment]
好吧，忘了recursive参数了

**Comment by leichunfeng** [comment]
请使用 README 中介绍的命令一键克隆，谢谢。

发自我的 iPhone
