### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by a345957280** [leichunfeng/MVVMReactiveCocoa#60]
我下载了你的代码,也 pod install 了.提示找不到ReactiveCocoa.h,   我 pod 导入进去又报错差OctoKit....请问下这是怎么回事呢?   pod  38.2                xcode  6.4

**Comment by leichunfeng** [comment]
请使用 README 中的命令一键克隆。

发自我的 iPhone

**Comment by a345957280** [comment]
这次用的  git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git   克隆到本地了.
再打开报错.

Check dependencies
警告信息
The file “Debug.xcconfig” couldn’t be opened because there is no such file. (/Users/admin/Downloads/testMVVM/MVVMReactiveCocoa/OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/xcconfigs/Base/Configurations/Debug.xcconfig)
The file “iOS-Framework.xcconfig” couldn’t be opened because there is no such file. (/Users/admin/Downloads/testMVVM/MVVMReactiveCocoa/OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/xcconfigs/iOS/iOS-Framework.xcconfig)

报错信息
Build setting PRODUCT_NAME undefined

**Comment by leichunfeng** [comment]
你是用 Xcode 7 的吗？

**Comment by a345957280** [comment]
我是xcode 6.4

**Comment by a345957280** [comment]
Version 6.4 (6E35b)

**Comment by leichunfeng** [comment]
我的是用 Xcode 7 运行过了哦，估计是不能向下兼容吧？

**Comment by leichunfeng** [comment]
你在 clone 过程中有出现什么错误吗？

**Comment by a345957280** [comment]
更新到 Xcode7, 工程也重新克隆了一遍.终于可以了...可能是 Xcode6.4 不行吧...

**Comment by leichunfeng** [comment]
恩，我猜测也是这样的吧，高版本的 Xcode 打开过的工程，低版本的 Xcode 可能会不兼容吧。

**Comment by luohuaDev** [comment]
原来如此。

**Comment by magic3584** [comment]
我按着README中的命令clone后然后pod install / update，报的错和3楼的一致。
Xcode7.1.1

**Comment by CZ-Star** [comment]
我按着README中的命令clone后然后pod install / update，报的错和3楼的一致。
Xcode7.1.1

**Comment by leichunfeng** [comment]
不需要再运行 pod install / update 的

**Comment by adronfan** [comment]
用readme里面的命令克隆的，xcode是7.2，还是不能够运行，报错同上，啊啊啊，

**Comment by leichunfeng** [comment]
我再试试看

**Comment by Ailix** [comment]
是需要安装Carthage吗

**Comment by leichunfeng** [comment]
应该不需要吧，现在工程太大了，我在想办法给这个库瘦身，不然用我公司的网速我自己都 clone 不下了，囧。

**Comment by leichunfeng** [comment]
我已经将这个库的大小从 `117.55 MiB` 缩减到了 `7.24 MiB` ，请根据 `README` 中的命令进行 `clone` 哈，我亲测可用的了，非常感谢你们的反馈哈：

``` objc
git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install --no-repo-update
```
