### ISSUE TITLE
Feedback from jbudde

### ISSUE THREAD

**Issue by jbudde** [leichunfeng/MVVMReactiveCocoa#85]
I'm not sure how this repository ended up on my phone, I've only been watching how this stuff works because I've had a "hacker" for over 4 years and your site always seems to link one way or another along with aws and open source.  I don't no how to "pull" or make a request and don't know what to do with it if I had requested it.  Can someone help me please.  Thank you for your support.  Jamieloubpjbb@aol.co.uk

**Comment by leichunfeng** [comment]
I can't understand what you mean, the url of the repository is https://github.com/leichunfeng/MVVMReactiveCocoa.
