### ISSUE TITLE
按README中所述步骤clone，报错

### ISSUE THREAD

**Issue by kiwh77** [leichunfeng/MVVMReactiveCocoa#87]
![issus](https://cloud.githubusercontent.com/assets/7447615/12188627/05793fa8-b5f2-11e5-8f24-595041460821.png)
我严格按照README中的三个命令来执行，最后还是报错
大致内容:
OctoKit iOS ->  Umbrella header for module 'Mantle' does not include header
MVVMReactiveCocoa-Prefix.pch -> 'ReactivewCocoa/ReactiveCocoa.h' file not found 
Reachability.h -> Include of non-modular header inside framework module

**Comment by leichunfeng** [comment]
你用的 `CocoaPods` 是多少版本的呢？

**Comment by kiwh77** [comment]
0.39,0

**Comment by leichunfeng** [comment]
我用的是 0.38.2 的版本，你用 0.39.0 pod 其他项目会有问题吗？

**Comment by kiwh77** [comment]
不会呀，我一般在github上看到项目都是用的git clone的，都是正常的，事实上也刚刚clone你的项目，步骤显示都正常

**Comment by leichunfeng** [comment]
可以麻烦你安装到 0.38.2 试试看吗？帮我验证下是否是 pod 的版本问题。

**Comment by kiwh77** [comment]
好，我试试

**Comment by kiwh77** [comment]
试了，把CocoaPods版本降成0.38.2还是这样
![issus](https://cloud.githubusercontent.com/assets/7447615/12189224/d21b3ec2-b5f6-11e5-89a4-14088b9f9c1f.png)

**Comment by leichunfeng** [comment]
奇怪了，我这边测试了下是可以的哦，你用 pod update --no-repo-update 试试看？

**Comment by kiwh77** [comment]
额，还是这样...
![issus](https://cloud.githubusercontent.com/assets/7447615/12190099/87779cae-b5ff-11e5-84d0-993fa4b83685.png)

**Comment by leichunfeng** [comment]
你确定克隆的时候有加 `--recursive` 参数吗？

**Comment by kiwh77** [comment]
确定

**Comment by leichunfeng** [comment]
我和同事都再用 `README` 中的命令重新完整地 `clone` 了一次，都是可以的哦，麻烦你用 `SourceTree` 再试一次看看？

**Comment by yeziahehe** [comment]
同样遇到了这个问题
`git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git`的时候最后会出现
`Failed to recurse into submodule path 'OctoKit'`

**Comment by leichunfeng** [comment]
麻烦提供一下截图哈，会不会是网络问题呢，连着上 VPN 试试看？

**Comment by yeziahehe** [comment]
![2016-01-09 22 49 16](https://cloud.githubusercontent.com/assets/8090437/12216621/463ecc42-b723-11e5-979b-c79046ff91db.png)

**Comment by leichunfeng** [comment]
earyly EOF 的错误应该是 RAC 的库太大，因为 https 方式的大小有限制，我考虑下是否全部替换成 SSH 的方式

**Comment by leichunfeng** [comment]
麻烦运行一下这个命令后再 clone 试试：
git config --global --add core.compression -1

git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install

**Comment by yeziahehe** [comment]
@leichunfeng 好的。我来试一下。

**Comment by leichunfeng** [comment]
非常感谢

**Comment by yeziahehe** [comment]
@leichunfeng 确实可以，速度明显快了，可以请教下原因嘛？

**Comment by leichunfeng** [comment]
首先，下面这个错误产生的原因应该是用 `https` 方式 `clone` 仓库的时候有大小的限制：

``` objc
error: RPC failed; result=56, HTTP code = 200B | 0 bytes/s
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

其中，一种可行的解决方案是将所有仓库的链接都替换成 `SSH` 的方式，但是这种方案的缺点是要求用户在 `GitHub` 上配置了 `SSH key`，要求有点高。所以，我还是坚持推荐用户用 `https` 的方式来 `clone` 本仓库。然后，我 `Google` 了下，发现了这个比较简单的解决方案，链接如下：

[https://web.archive.org/web/20130713101512/http://hackerslab.eu/blog/2012/02/git-early-eof-fatal-error](https://web.archive.org/web/20130713101512/http://hackerslab.eu/blog/2012/02/git-early-eof-fatal-error)
[https://cristinallamas.wordpress.com/2013/11/02/git-error-the-remote-end-hung-up-unexpectedly/](https://cristinallamas.wordpress.com/2013/11/02/git-error-the-remote-end-hung-up-unexpectedly/)

**Comment by leichunfeng** [comment]
再次感谢你帮忙验证这个解决方案，我已经更新了仓库的 `README` ，在 `Common problems` 小节进行了说明。

**Comment by yeziahehe** [comment]
@leichunfeng 不客气，上次您才加我QQ，帮我解决了封装的一些疑问，还对我的博客做了指正，谢谢你！
