### ISSUE TITLE
用cocopods搭建失败

### ISSUE THREAD

**Issue by DexSinis** [leichunfeng/MVVMReactiveCocoa#89]
Analyzing dependencies
Pre-downloading: `OcticonsIOS` from `https://github.com/jacksonh/OcticonsIOS.git`, commit `4bd3b21`
Fetching podspec for `WXTabBarController` from `WXTabBarController`
[!] No podspec found for `WXTabBarController` in `WXTabBarController`
 就算是这个改了还是有其他依赖的问题，请问podfile的配置确定可以吗？

**Comment by leichunfeng** [comment]
请问下你是使用 `README` 中介绍的命令吗？

**Comment by nitxc** [comment]
Yes，I hava same a question.pod install --no-repo-update 。
Pre-downloading: `OcticonsIOS` from `https://github.com/jacksonh/OcticonsIOS.git`, commit `4bd3b21`
Fetching podspec for `WXTabBarController` from `WXTabBarController`
[!] No podspec found for `WXTabBarController` in `WXTabBarController`

**Comment by leichunfeng** [comment]
请问下你们是使用 `README` 中介绍的命令吗？

**Comment by nitxc** [comment]
是的，我是用Sources Tree 克隆下来的。所以直接跳转到文件夹下。执行的命令，能否给个pod install 的项目给我。
![aef25abb-94ef-437d-a745-a9cda7474fbd](https://cloud.githubusercontent.com/assets/10385969/12215502/1272de40-b6fa-11e5-99fd-cde8e8a12472.png)

**Comment by leichunfeng** [comment]
请直接使用 pod install 试试？

**Comment by leichunfeng** [comment]
去掉 `pod install --no-repo-update` 中的选项 `--no-repo-update` ，直接使用 `pod install` 应该就可以解决这个问题了，我已经更新了 `README` 中的命令描述了：

``` objc
git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install
```

**Comment by leichunfeng** [comment]
请帮忙验证一下是否可行，非常感谢。

**Comment by springxiao** [comment]
试了一发，还是不行哦

**Comment by leichunfeng** [comment]
报什么错呢？

**Comment by springxiao** [comment]
ok了，是我自己的问题，clone时没加 --recursive
