### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by Gavin123** [leichunfeng/MVVMReactiveCocoa#90]
pod install --verbose --no-repo-update  not install

please this problem ,thanks!!!!

**Comment by leichunfeng** [comment]
``` objc
git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install
```

请直接使用 `pod install` ，谢谢。

**Comment by Gavin123** [comment]
执行pod install 没反应，等待时间太长
![image](https://cloud.githubusercontent.com/assets/5095402/12219921/0fad3c8e-b793-11e5-8667-0d0d4877aff3.png)

**Comment by leichunfeng** [comment]
只能等待了，时间需要比较长是因为 CocoaPods 在更新本地的索引，太慢的话连接上 VPN 再试试。

**Comment by nitxc** [comment]
已经能启动了，但是登陆了有闪退现象。

**Comment by leichunfeng** [comment]
是最新的代码吗？一定重现的吗？

**Comment by nitxc** [comment]
恩，最新的代码。
![13b28e51-98a4-4078-8535-e7cc7845370a](https://cloud.githubusercontent.com/assets/10385969/12228029/b02f739c-b870-11e5-99ca-443ea2bd8a16.png)

**Comment by leichunfeng** [comment]
恩，非常感谢你反馈哈，可以加我的 QQ307213080 聊吗？可能得借你的账号用一下哦。

**Comment by leichunfeng** [comment]
@Gavin123 请问下你的问题解决了吗？

**Comment by fengzhu1234** [comment]
![Uploading (UV0{({~EK45C(9PP~Q88`I.jpg…]()

**Comment by fengzhu1234** [comment]
图片怎么上传的，我的错误图片不会上传

**Comment by leichunfeng** [comment]
直接拖上来，等待上传完成

**Comment by fengzhu1234** [comment]
你的工程我一直运行不了，是什么原因呢

**Comment by fengzhu1234** [comment]
我的qq  2412677657@qq.com 可以加个好友吗

**Comment by chukuanglxs** [comment]
cd+MVVMReactiveCocoa-master  
pod update --verbose --no-repo-update 运行出现下面的错误****
“ReactiveCocoa／ReactiveCocoa.h”file not found 的错误。。。新手请指点一下谢谢

**Comment by 2yscw** [comment]
编译的时候报“ReactiveCocoa／ReactiveCocoa.h”file not found 的错误，麻烦指导一下，谢谢。

**Comment by jxxxyz** [comment]
git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
cd MVVMReactiveCocoa
pod install

编译的时候报“ReactiveCocoa／ReactiveCocoa.h”file not found 的错误

**Comment by leichunfeng** [comment]
请用 README 中的命令进行 clone

**Comment by jxxxyz** [comment]
Last login: Thu Jun 30 14:09:53 on ttys000
localhost:~ fhhd$ git clone --recursive https://github.com/leichunfeng/MVVMReactiveCocoa.git
Cloning into 'MVVMReactiveCocoa'...
remote: Counting objects: 11354, done.
remote: Total 11354 (delta 0), reused 0 (delta 0), pack-reused 11354
Receiving objects: 100% (11354/11354), 9.62 MiB | 28.00 KiB/s, done.
Resolving deltas: 100% (7189/7189), done.
Checking connectivity... done.
Submodule 'OctoKit' (https://github.com/leichunfeng/octokit.objc.git) registered for path 'OctoKit'
Cloning into 'OctoKit'...
remote: Counting objects: 5843, done.
remote: Total 5843 (delta 0), reused 0 (delta 0), pack-reused 5843
Receiving objects: 100% (5843/5843), 1.60 MiB | 169.00 KiB/s, done.
Resolving deltas: 100% (3702/3702), done.
Checking connectivity... done.
Submodule path 'OctoKit': checked out 'bd2ad04b0947ca0717c787335db5ed1b686f81d7'
Submodule 'Carthage/Checkouts/Mantle' (https://github.com/Mantle/Mantle.git) registered for path 'Carthage/Checkouts/Mantle'
Submodule 'Carthage/Checkouts/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Carthage/Checkouts/Nimble'
Submodule 'Carthage/Checkouts/Quick' (https://github.com/Quick/Quick.git) registered for path 'Carthage/Checkouts/Quick'
Submodule 'Carthage/Checkouts/ReactiveCocoa' (https://github.com/ReactiveCocoa/ReactiveCocoa.git) registered for path 'Carthage/Checkouts/ReactiveCocoa'
Submodule 'Carthage/Checkouts/xcconfigs' (https://github.com/jspahrsummers/xcconfigs.git) registered for path 'Carthage/Checkouts/xcconfigs'
Submodule 'External/AFNetworking' (https://github.com/github/AFNetworking.git) registered for path 'External/AFNetworking'
Submodule 'External/ISO8601DateFormatter' (https://github.com/boredzo/iso-8601-date-formatter.git) registered for path 'External/ISO8601DateFormatter'
Submodule 'External/OHHTTPStubs' (https://github.com/github/OHHTTPStubs.git) registered for path 'External/OHHTTPStubs'
Cloning into 'Carthage/Checkouts/Mantle'...
remote: Counting objects: 5392, done.
remote: Total 5392 (delta 0), reused 0 (delta 0), pack-reused 5391
Receiving objects: 100% (5392/5392), 1.45 MiB | 28.00 KiB/s, done.
Resolving deltas: 100% (3355/3355), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle': checked out 'f797bd4837b61d37847a4833024aab268599a681'
Submodule 'Carthage.checkout/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Carthage/Checkouts/Nimble'
Submodule 'Carthage.checkout/Quick' (https://github.com/Quick/Quick.git) registered for path 'Carthage/Checkouts/Quick'
Submodule 'Carthage.checkout/xcconfigs' (https://github.com/jspahrsummers/xcconfigs.git) registered for path 'Carthage/Checkouts/xcconfigs'
Cloning into 'Carthage/Checkouts/Nimble'...
remote: Counting objects: 4567, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4567 (delta 0), reused 0 (delta 0), pack-reused 4564
Receiving objects: 100% (4567/4567), 949.49 KiB | 138.00 KiB/s, done.
Resolving deltas: 100% (3111/3111), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle/Carthage/Checkouts/Nimble': checked out '6f787eeb75b2fa71464981f28b3dc8d7bd532e69'
Cloning into 'Carthage/Checkouts/Quick'...
remote: Counting objects: 5200, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5200 (delta 0), reused 0 (delta 0), pack-reused 5198
Receiving objects: 100% (5200/5200), 1.66 MiB | 253.00 KiB/s, done.
Resolving deltas: 100% (3138/3138), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle/Carthage/Checkouts/Quick': checked out 'b0e98286db7e9d1f1e73cd4e69eac2aae2a1e3f8'
Submodule 'Externals/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Externals/Nimble'
Cloning into 'Externals/Nimble'...
remote: Counting objects: 4567, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4567 (delta 0), reused 0 (delta 0), pack-reused 4564
Receiving objects: 100% (4567/4567), 949.49 KiB | 27.00 KiB/s, done.
Resolving deltas: 100% (3111/3111), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle/Carthage/Checkouts/Quick/Externals/Nimble': checked out '56c3b79d5a32686fe5529d7aa305000b489ebdaa'
Cloning into 'Carthage/Checkouts/xcconfigs'...
remote: Counting objects: 637, done.
remote: Total 637 (delta 0), reused 0 (delta 0), pack-reused 637
Receiving objects: 100% (637/637), 114.58 KiB | 29.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Mantle/Carthage/Checkouts/xcconfigs': checked out '6c64238566ef1126f1b7994aa9e6719229c50451'
Cloning into 'Carthage/Checkouts/Nimble'...
remote: Counting objects: 4567, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4567 (delta 0), reused 0 (delta 0), pack-reused 4564
Receiving objects: 100% (4567/4567), 949.49 KiB | 88.00 KiB/s, done.
Resolving deltas: 100% (3111/3111), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Nimble': checked out '6f787eeb75b2fa71464981f28b3dc8d7bd532e69'
Cloning into 'Carthage/Checkouts/Quick'...
remote: Counting objects: 5200, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5200 (delta 0), reused 0 (delta 0), pack-reused 5198
Receiving objects: 100% (5200/5200), 1.66 MiB | 204.00 KiB/s, done.
Resolving deltas: 100% (3138/3138), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Quick': checked out 'b0e98286db7e9d1f1e73cd4e69eac2aae2a1e3f8'
Submodule 'Externals/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Externals/Nimble'
Cloning into 'Externals/Nimble'...
remote: Counting objects: 4567, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4567 (delta 0), reused 0 (delta 0), pack-reused 4564
Receiving objects: 100% (4567/4567), 949.49 KiB | 24.00 KiB/s, done.
Resolving deltas: 100% (3111/3111), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/Quick/Externals/Nimble': checked out '56c3b79d5a32686fe5529d7aa305000b489ebdaa'
Cloning into 'Carthage/Checkouts/ReactiveCocoa'...
remote: Counting objects: 41805, done.
remote: Compressing objects: 100% (231/231), done.
remote: Total 41805 (delta 153), reused 0 (delta 0), pack-reused 41573
Receiving objects: 100% (41805/41805), 16.01 MiB | 194.00 KiB/s, done.
Resolving deltas: 100% (24858/24858), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa': checked out '32364b9040dee9975053398bcf89f3f94a8341cd'
Submodule 'Carthage/Checkouts/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Carthage/Checkouts/Nimble'
Submodule 'Carthage/Checkouts/Quick' (https://github.com/Quick/Quick.git) registered for path 'Carthage/Checkouts/Quick'
Submodule 'Carthage/Checkouts/xcconfigs' (https://github.com/jspahrsummers/xcconfigs.git) registered for path 'Carthage/Checkouts/xcconfigs'
Cloning into 'Carthage/Checkouts/Nimble'...
remote: Counting objects: 4567, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4567 (delta 0), reused 0 (delta 0), pack-reused 4564
Receiving objects: 100% (4567/4567), 949.49 KiB | 68.00 KiB/s, done.
Resolving deltas: 100% (3111/3111), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Nimble': checked out '8927113f877f32c8a01b41b746c4ac261b42c48e'
Cloning into 'Carthage/Checkouts/Quick'...
remote: Counting objects: 5200, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 5200 (delta 0), reused 0 (delta 0), pack-reused 5198
Receiving objects: 100% (5200/5200), 1.66 MiB | 23.00 KiB/s, done.
Resolving deltas: 100% (3138/3138), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick': checked out '8bf96f708924d728dab5f0cf7543b6f1b896a209'
Submodule 'Externals/Nimble' (https://github.com/Quick/Nimble.git) registered for path 'Externals/Nimble'
Cloning into 'Externals/Nimble'...
remote: Counting objects: 4567, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4567 (delta 0), reused 0 (delta 0), pack-reused 4564
Receiving objects: 100% (4567/4567), 949.49 KiB | 69.00 KiB/s, done.
Resolving deltas: 100% (3111/3111), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/Quick/Externals/Nimble': checked out '6a9a1036c0604119c5567e45916149e16f251152'
Cloning into 'Carthage/Checkouts/xcconfigs'...
remote: Counting objects: 637, done.
remote: Total 637 (delta 0), reused 0 (delta 0), pack-reused 637
Receiving objects: 100% (637/637), 114.58 KiB | 32.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/ReactiveCocoa/Carthage/Checkouts/xcconfigs': checked out '2e77204b59c3d97c24e5dd34966fb32c231194f0'
Cloning into 'Carthage/Checkouts/xcconfigs'...
remote: Counting objects: 637, done.
remote: Total 637 (delta 0), reused 0 (delta 0), pack-reused 637
Receiving objects: 100% (637/637), 114.58 KiB | 42.00 KiB/s, done.
Resolving deltas: 100% (227/227), done.
Checking connectivity... done.
Submodule path 'OctoKit/Carthage/Checkouts/xcconfigs': checked out 'b09b4b63235b760a3a48a8dd19c0415aaaa8f269'
Cloning into 'External/AFNetworking'...
remote: Counting objects: 10866, done.
remote: Total 10866 (delta 0), reused 0 (delta 0), pack-reused 10866
Receiving objects: 100% (10866/10866), 3.75 MiB | 586.00 KiB/s, done.
Resolving deltas: 100% (6994/6994), done.
Checking connectivity... done.
Submodule path 'OctoKit/External/AFNetworking': checked out 'e364bf509249c43282784b9595b3284145ddbba9'
Cloning into 'External/ISO8601DateFormatter'...
remote: Counting objects: 1165, done.
remote: Total 1165 (delta 0), reused 0 (delta 0), pack-reused 1165
Receiving objects: 100% (1165/1165), 285.00 KiB | 43.00 KiB/s, done.
Resolving deltas: 100% (704/704), done.
Checking connectivity... done.
Submodule path 'OctoKit/External/ISO8601DateFormatter': checked out '35f4248b2747dee9716c9f59ccada16862a5278c'
Cloning into 'External/OHHTTPStubs'...
remote: Counting objects: 1398, done.
remote: Total 1398 (delta 0), reused 0 (delta 0), pack-reused 1398
Receiving objects: 100% (1398/1398), 349.09 KiB | 58.00 KiB/s, done.
Resolving deltas: 100% (892/892), done.
Checking connectivity... done.
Submodule path 'OctoKit/External/OHHTTPStubs': checked out '8761af63dc87ef8dd3944f2248ac4e1f6256c4c8'
localhost:~ fhhd$ cd MVVMReactiveCocoa
localhost:MVVMReactiveCocoa fhhd$ pod install
Analyzing dependencies
Pre-downloading: `LCFInfiniteScrollView` from `https://github.com/leichunfeng/LCFInfiniteScrollView.git`, commit `790c256212c610c72127e57f945fbe4064cde98a`
Pre-downloading: `OcticonsIOS` from `https://github.com/jacksonh/OcticonsIOS.git`, commit `4bd3b21`
Downloading dependencies
Installing Appirater (2.0.5)
Installing DZNEmptyDataSet (1.5.2)
Installing FMDB (2.6.2)
Installing FormatterKit (1.8.1)
Installing GPUImage (0.1.7)
Installing IQKeyboardManager (3.2.0.3)
Installing LCFInfiniteScrollView (0.1)
Installing MBProgressHUD (0.9.2)
Installing MKNetworkKit (0.87)
Installing OcticonsIOS (0.0.2)
Installing Ono (1.2.2)
Installing Reachability (3.1.1)
Installing Reveal-iOS-SDK (1.6.2)
Installing SDVersion (2.6)
Installing SDWebImage (3.7.6)
Installing SSKeychain (1.2.3)
Installing SVPullToRefresh (0.4.1)
Installing UIActivityIndicator-for-SDWebImage (1.2)
Installing UMengSocial (4.4)
Installing WebViewJavascriptBridge (4.1.5)
Installing YYKit (1.0.5)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `MVVMReactiveCocoa.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 20 dependencies from the Podfile and 21
total pods installed.
localhost:MVVMReactiveCocoa fhhd$ 
============================ge=======
这样编译后 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IQKeyboardManager", referenced from:
      objc-class-ref in MRCAppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by leichunfeng** [comment]
你的 Xcode 版本是多少的？我用 7.3.1 和 8 都没有问题的

**Comment by jxxxyz** [comment]
版本一样的 Version 7.3.1 (7D1014)

**Comment by leichunfeng** [comment]
你先 Google 一下看看能否解决，我有时间再看看

**Comment by xiaolong11** [comment]
编译的时候报“ReactiveCocoa／ReactiveCocoa.h”file not found 的错误，麻烦指导一下，谢谢。

**Comment by leichunfeng** [comment]
请直接使用 `README` 中的命令进行克隆。
