### ISSUE TITLE
雷大侠，求MVVMReactiveCocoa中的框架说明

### ISSUE THREAD

**Issue by Zdada** [leichunfeng/MVVMReactiveCocoa#94]

**Comment by leichunfeng** [comment]
?

**Comment by Zdada** [comment]
小弟目前正在学习ReactiveCocoa，暂时还在入门阶段，阅读您的代码让我受益匪浅。我想学习您的框架 在我的项目中进行应用，但是发现很多东西不懂很难移植，请赐教啊！🙏

**Comment by leichunfeng** [comment]
过奖了哈，你的 QQ 昵称是`平凡-简单`吗？我看到你加 RAC 的群了，目前可以直接在群里面交流下，近期我会专门写一篇文章介绍这个项目的哈。

**Comment by Zdada** [comment]
是的，感谢 感谢

**Comment by leichunfeng** [comment]
你要的文章[《MVVM With ReactiveCocoa》](http://blog.leichunfeng.com/blog/2016/02/27/mvvm-with-reactivecocoa/)终于来了，久等了哈。

**Comment by Zdada** [comment]
太好了！感谢大神啊！
