### ISSUE TITLE
项目里没有MVVMReactiveCocoa.xcworkspace？

### ISSUE THREAD

**Issue by QiuDaniel** [leichunfeng/MVVMReactiveCocoa#99]
如题，下载了zip包，解压缩后没发现该文件。clone项目，也没发现。

**Comment by leichunfeng** [comment]
请直接用 `README` 中的命令操作，`MVVMReactiveCocoa.xcworkspace` 会通过 `pod install` 命令自动生成，为了减少库的大小，所以不想提交上去。

**Comment by QiuDaniel** [comment]
![image](https://cloud.githubusercontent.com/assets/8155698/13416452/a5d1405c-df9d-11e5-9052-9d2ecc11e036.png)
pod install 过程中的提示。是我的cocoapods版本低的缘故吗？

**Comment by leichunfeng** [comment]
我用的是 0.38.2

**Comment by QiuDaniel** [comment]
已解决，cocoapods本地缓存的版本比podlock中低的原因，更新即刻。

**Comment by leichunfeng** [comment]
Nice

**Comment by leichunfeng** [comment]
可以描述一下详细的解决步骤吗？可以供其他人参考下

**Comment by QiuDaniel** [comment]
当在pod install的过程中出现上述我提到的问题：
1.执行pod setup，使本地的cocoapods缓存库得到更新，如果该步执行完之后没有其他问题。可继续执行pod install。若遇到"CocoaPods was not able to update the `master` repo"，执行步骤2
2.执行pod repo update --verbose，成功后执行pod install

**Comment by leichunfeng** [comment]
好的，感谢哈，目标就是要更新本地的索引吧
